name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 🚢 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Push To Gitlab
        run: |
          echo Starting to push repo to gitlab
          git remote set-url origin "https://yashpokar:${{ secrets.GITLAB_TOKEN }}@gitlab.com/yashpokar/agrojet-site-mirror.git"
          git push origin master -f
